### PR TITLE
AW-Implemented RiderApplication Table&Form Component

### LINKED ISSUE #42: Rider Application Issue 3&4 (Form & Table Components)

### PR DESCRIPTION
**Pull request by Kanagawa-okiNamiUra**
In this PR, I implemented RiderApplication Table&Form. I also updated currentUserFixture file to include a user that only has the role ROLE_MEMBER (in the original file every one with "ROLE_MEMBER" has "ROLE_ADMIN"). 100% mutation/line coverage.

A few implementation details to note:
- The member view and admin view for the data field (data in the RiderApplication.java) are the same. While it is explained in the EPIC instruction how the table is simplified for user view, I think it should be the same for admins as the admin will only require the details according to the status of an application. (for example, to approve/decline when status=pending, to examine an appeal from the student when an application is mistakenly declined (status=declined))

- Neither the table nor the form is viewable as of now on my running instance because I made no changes to App.js/ AppVanBar.js so please check the screenshots from my local storybook below.

1. Form component:

- Notice the email field is shown but not editable
- Notice the Description column is full width, six lines high, and has an extra label below it (as is specified in the instruction)
image

- Both fields are required for an application
image

- Perm Number has to contain 7 characters:
image
image

2. Table Component:
- Member's view:
image
-Cancel Button asks for Confirmation:
image
-Admin's view:
image

For whether the button navigates to the correct URL, please check my testfilles.

Close #42

### CODE REVIEW

**Comment by Kanagawa-okiNamiUra** [comment]
This should conclude Issue 3 and Issue 4 from EPIC#14

**Comment by Danny-You** [comment]
The author mentions that he might add some more features to this PR, so we will wait for the additional features then starting reviewing by tonight.

**Comment by Kanagawa-okiNamiUra** [comment]
After discussing with Guy, I realized the notes field should show up in the form when an admin logs in. However, this might require my form function to take in one more parameter currentUser. I’ll work on it later when I attempt the admin page. For now, I’ll keep it as is in this PR as I do not expect any problem when I implement member pages. Please give it a review now.

**Review by pconrad — APPROVED** [review]
LGTM...  I know you are doing some more work on this, but lets get this merged now...

**Review by Danny-You — APPROVED** [review]
LGTM! Ready to be reviewed by TA / Instructor

**Pull request merged**
